# Generated by Django 5.2.8 on 2025-11-30 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер теплицы')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь (кв.м)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Теплица',
                'verbose_name_plural': 'Теплицы',
            },
        ),
        migrations.CreateModel(
            name='VegetableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название культуры')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип овощной культуры',
                'verbose_name_plural': 'Типы овощных культур',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид работ')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид работ',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(verbose_name='Дата посадки')),
                ('planned_harvest_date', models.DateField(verbose_name='Планируемая дата сбора урожая')),
                ('actual_harvest_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата сбора урожая')),
                ('status', models.CharField(choices=[('planned', 'Запланирована'), ('planted', 'Посажена'), ('growing', 'Растет'), ('harvested', 'Собрана')], default='planned', max_length=20, verbose_name='Статус')),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.greenhouse', verbose_name='Теплица')),
                ('vegetable_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenhouse.vegetabletype', verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Посадка',
                'verbose_name_plural': 'Посадки',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(verbose_name='Дата сбора')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Количество')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('piece', 'шт'), ('box', 'ящик')], default='kg', max_length=20, verbose_name='Единица измерения')),
                ('quality', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('average', 'Среднее'), ('poor', 'Плохое')], default='good', max_length=20, verbose_name='Качество')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.planting', verbose_name='Посадка')),
            ],
            options={
                'verbose_name': 'Урожай',
                'verbose_name_plural': 'Урожай',
            },
        ),
        migrations.AddField(
            model_name='greenhouse',
            name='vegetable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenhouse.vegetabletype', verbose_name='Тип выращиваемой культуры'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.planting', verbose_name='Посадка')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='greenhouse.worktype', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'График работ',
                'verbose_name_plural': 'Графики работ',
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_volume', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Объем воды (л)')),
                ('fertilizer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Количество удобрений (кг)')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Трудозатраты (часы)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.workschedule', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Затраты ресурсов',
                'verbose_name_plural': 'Затраты ресурсов',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_after_planting', models.IntegerField(help_text='0 - день посадки', verbose_name='Дней после посадки')),
                ('duration_days', models.IntegerField(default=1, verbose_name='Продолжительность (дней)')),
                ('vegetable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.vegetabletype', verbose_name='Тип культуры')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse.worktype', verbose_name='Вид работ')),
            ],
            options={
                'verbose_name': 'Шаблон графика',
                'verbose_name_plural': 'Шаблоны графиков',
                'ordering': ['vegetable_type', 'days_after_planting'],
            },
        ),
    ]
