# Generated by Django 5.2.8 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='greenhouses'),
        ),
    ]
